### ISSUE TITLE
next.js bootstrap 에러

### ISSUE THREAD

**Issue by uyggnodkrap** [junhyeukkwon/M-Invitation#3]
부트스트랩 템플릿 받고 npm install이 안됩니다!

npm ERR! code 1 오류 뜨면서 npm이 안받아집니다 😥

**Comment by uiet312** [comment]
저도 설치가 안되길래 설치된 module을 적용해서 해결했습니다!

**Comment by uiet312** [comment]
혹시 npm error code 1 이런 에러 뜨면서 설치가 안되시나요?

**Comment by uiet312** [comment]
저는 설치된 modul파일 받아와서 해결했습니다!

**Comment by junhyeukkwon** [comment]
![image](https://user-images.githubusercontent.com/85923524/173286863-b20442c7-1252-4f62-b424-2f7420732caf.png)
npm install --save --legacy-peer-deps 명령어 실행을 했습니다.
다음 npm install react-paypal-express-checkout --save --legacy-peer-deps 명령어를 실행하고 npm run dev 를 실행했지만, Missing script: "dev" 로 module의 이상이 있음을 확인했습니다.

**Comment by uyggnodkrap** [comment]
> ![image](https://user-images.githubusercontent.com/85923524/173286863-b20442c7-1252-4f62-b424-2f7420732caf.png) npm install --save --legacy-peer-deps 명령어 실행을 했습니다. 다음 npm install react-paypal-express-checkout --save --legacy-peer-deps 명령어를 실행하고 npm run dev 를 실행했지만, Missing script: "dev" 로 module의 이상이 있음을 확인했습니다.

역시... node_modules 를 받아서 직접 넣는 수 밖에 없겠네요 😭
